# Site settings
title: Bex Jones
email: bex@bexjones.com
description: > # this means to ignore newlines until "baseurl:"
 Bex Jones is an Anthropologist and Filmmaker from the UK. Through bexjones.com you can see samples of her work and up coming projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bexjones.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  bexjones

# Build settings
markdown: kramdown
